# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='worker',
            name='LastName',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
