# Generated by Django 2.1.4 on 2018-12-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0002_auto_20181020_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='CurrentProject',
            field=models.ForeignKey(blank=True, on_delete=True, to='Lab.Project'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='FirstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='LastName',
            field=models.CharField(max_length=100),
        ),
    ]
