# Generated by Django 2.1.4 on 2018-12-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0003_auto_20181213_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Body', models.CharField(max_length=10000000)),
            ],
        ),
    ]
