# Generated by Django 2.1.4 on 2018-12-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0004_blockpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockpost',
            name='Body',
            field=models.TextField(max_length=10000000),
        ),
    ]
